#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Modeling of synapses between mossy fibers and unipolar brush cells (UBCs) in the cerebellum.

The goal of this modeling is to investigate the properties of a specific type of synapses in the cerebellum: between mossy fibers (MF) and unipolar brush cells (UBCs).
More precisely, it consists in assessing the effects of the morphology of a synapse on the signal transmission.
For this purpose, the package achieves the following tasks:
    1. Modeling the morphology of synapses.
    2. Simulating their behavior in response to a stimulation pattern (events of glutamate release).

Usage
-------
The Jupyter notebook provided in the package is designed to guide the user in the exploration of the functionalities.

Structure of the package
------------------------
PCBS_UBC_synapse/
│
├── README.md
├── UBC_usage_demo.ipynb    <- notebook to guide the user into the project
├── UBC_synapse/            <- source codes directory
│   └── __init__.py
│   └── synapse_model.py
│   └── synapse_morph.py
│   └── stimulation_pattern.py
│   └── stimulation_sim.py
│   └── manage_data.py
│   └── visuaize.py
│   └── c_code/
│       └── run_simulation.c
│       └── run_simulation.so
├── UBC_data/               <- directory for storing the data generated by running the codes
│   └── synapses_register.csv
│   └── syn0/
│       └── responses_syn0_register.csv
│       └── resp0_syn0/
│           └── coords.csv
│           └── resgluxx-xx.csv
│           └── resAMPAtot.csv
│           └── resV.csv
├── UBC_installation/       <- directory for the project installation setup
│   └── environment.yml     <- list of dependencies, file usable by conda
│   └── requirements.txt    <- list of dependencies, file usable by virtualenv
│   └── setup.py            <- configuration file
│   └── MANIFEST.in         <- specification of the non-.py files to be included in the project
├── UBC_references/         <- directory for other documentation and resources
│   └── LICENSE.txt
│   └── AUTHORS.rst
│   └── fig1_cerebelllum_network.png
│   └── parameters.py

Modules
-------
All the Python modules are located in the directory `UBC_synapse/`. The C library is contained in the sub-folder `c_codes/`.
    * synapse_model - Class for building synapses objects. 
    * synapse_morph - Functions for building matrixes representing the morphology of a synapse.
    * stimulation_pattern - Class for generating sequences of stimulation events, under which the synapses' behaviors will be observed.
    * stim_sim - Functions for setting up a simulation sun, and interfacing with the C code. 
    * run_simulation (C code in `UBC_synapse/c_codes`) - Core computations for simulating the response of a synapse under a stimulation pattern.
    * manage_data - Functions for saving and retrieving the results.
    * visuaize - Functions for generating representations of the synapses' morphology and behaviors.
A more detailed documentation for individual modules is provided in each one, with their respective functions.

Data
-------
The synapses and the data generated by running the package can be saved in the directory `UBC_data/`, thanks to the methods of the class Synapse.
The file `register_syn.csv` keeps track of the saved synapses: 
    * the different instances are classified according to their attributes,
    * each saved synapse is referenced by an index (number).
Each saved synapse is associated to a sub-directory named `sny{index}`. One directory contains:
    * a file `responses_syn{index}_register.csv`, classifying the stimulation trials with this synapse, and referencing them by an index (number),
    * directories `resp{index}_syn{index}/`, one for each trial, containing the results.
For each stimulation trial, the results are made up of:
    * `coords.csv`: locations of the points on the synapse where the glutamate concentrations were recorded,
    * `resgluxx-xx.csv`: variations of the glutamate concentration at location xx-xx (row-column),
    * `resAMPAtot.csv`: evolution of the activation state of the post-synaptic AMPA receptors,
    * `resV.csv`: variations of the UBC's membrane potential.
"""

__authors__ = ("esther-poniatowski")
__contact__ = ("esther.poniatowski@ens.fr")
__version__ = "1.0.0"
__date__ = "01/01/2020"

print("UBC_synapse importation:")
from .synapse_model import Synapse
from .stimulation_pattern import Pattern
